server:
  port: 10086 # eureka server port

spring:
  application:
    name: eurekaserver # eureka 微服务的名称

eureka:
  client:
    service-url: # eureka 地址信息
      defaultZone: http://127.0.0.1:10086/eureka